duckdb/extension-ci-tools

makefiles/duckdb_extension.Makefile

Add a reusable makefile that can be used by out-of-tree extensions to: run Cmake builds, run tests, etc.

Add duckdb_extension.Makefile

---

makefiles/duckdb_extension.Makefile

This way, we can point the extension to a central checkout of duckdb/duckdb rather than dealing with the local git submodule during development.

Allow to override DuckDB source directory

---

.github/workflows/_extension_distribution.yml

Problem is that otherwise extension can't be linked, see https://github.com/duckdb/sqlite_scanner/actions/runs/9075702375/job/24936875420?pr=93#step:10:2120

Define DUCKDB_PLATFORM_RTOOLS when compiling for arch rtools

---

.github/workflows/_extension_distribution.yml

There is somethign funcky with ENV variables in containers, so the GITHUB_ENV is not working here

Use a different way to pass down DUCKDB_PLATFORM_RTOOLS variable

---

makefiles/duckdb_extension.Makefile

External linking step is now done as part of duckdb, so can (and should) be removed.

Fix Makefile for duckdb-wasm

---

makefiles/duckdb_extension.Makefile

So that we don't need a working Python setup for cleanup.

Separate make clean-python from make clean

---

.github/workflows/_extension_distribution.yml

this was actually broken: pr #29 actually broke this: ninja isn't installed in windows ci job.
Todo: we should add ci to this repo to avoid this

remove ninja from ci

---

.github/workflows/_extension_distribution.yml

CentOS 7 is hilariously old, but according to https://mayeut.github.io/manylinux-timeline we are not ready to give up just yet: ~26% of people are not yet on GLIBC 2.28 (which would be the next step up in manylinux-land). So for now we bandaid our manylinux builds. The fix here appears to do the trick, but I will keep an eye on https://github.com/pypa/manylinux/issues/1641 where a different/better solution might get proposed

Fix CentOS7 going EOL

---

makefiles/duckdb_extension.Makefile

This was accidentally broken in a recent PR

restore selectig build mode for msvc

---

.github/workflows/_extension_distribution.yml
makefiles/duckdb_extension.Makefile

allows use of the `_extension_distribution` and `_extension_deploy` reusable workflows in the community extension repo. 
What this also enables, is to easily setup a CI job in this repo that tests this repo against the extension template, which will allow us to actually run CI in PRs to this repository.
CI jobs using this workflow have been run in the `samansmink/community-extensions` repo here:
- with the `samansmink/duckdb-prql` repo (https://github.com/samansmink/community-extensions/actions/runs/9760448970)
- with the extension template (quack) extension (https://github.com/samansmink/community-extensions/actions/runs/9760461279)
Note the CI job for windows_rtools for  `samansmink/duckdb-prql` failed: but that simply is not yet supported, I will add windows_rtools to the excluded …

add support for community repo

---

.github/workflows/_extension_distribution.yml

Tests for this will be at:
* https://github.com/carlopi/duckdb-prql/actions/runs/9828432717
* https://github.com/carlopi/quack/actions/runs/9828404400/job/27132261289
Tradeoffs between approaches are not trivial, in particular we are temporarily doing without ccache, but I think this is the proper way out of this.

Unroll logic out of github action and into docker + script

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

restores building rust-based extensions by reverting the changes from https://github.com/duckdb/extension-ci-tools/pull/42 in favor of setting ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
We should properly fix this asap as ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION could be removed at any time.
This PR also adds a CI job to test this repo by building https://github.com/duckdb/extension-template and https://github.com/duckdb/duckdb_delta using this version of the ci tools.
Fixes failures like this:
```
There’s nothing that PPA owners can do about this for now, as the key is fully controlled internally by Launchpad.
More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
Error: retrieving gpg key timed out.
```
in the ubuntu18 setup script by completely removing that. In the process I …

Re-enable rust, fix ubuntu 18 failure

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

This will allow us to add more toolchains dynamically to enable more flexibility in building extensions that require extra toolchain setup.
We reduce the risk of an extension requiring some toolchain to be present to break other extension's CI

add option to enable extra toolchains, deprecated enable_rust

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

This adds support for fortran and openmp "toolchains".
The fortran "toolchain" ensures that a fortran compiler is present, and omp ensures that the compiler can use openmp.

Add support for fortran and openmp as toolchains

---

.github/workflows/_extension_distribution.yml

Semi-unsolicited PR, below small explanation on why this is needed. Also tagging @hannes as this is one of the changes we discussed on friday WRT the getting faiss extension in the community repo.
The previous method of setting the CC and friends environment variables causes some issues with some vcpkg ports. Sometimes a port must be compiled for the host, but when the CC env variable is set, this overwrites all settings. This leads to a situation where code that must be compiled for the host architecture (eg amd64) will be compiled with an arm64 cross-compiler.

Pass the compilers using CMAKE_XXX_COMPILER instead of XXX env variable

---

.github/workflows/_extension_distribution.yml

Hello! one last PR. This PRs adds the option for extensions to use their own fork of vcpkg. The use-case may be small, but I think the risk is also small, as this is just passing down the option to run-vcpkg. I hope this would be possible to add!

Allow vcpkg custom git url

---

.github/workflows/_extension_distribution.yml

Using the deprecated version is breaking the pipeline
It was working yesterday but I guess Github finally disabled the old versions.
Upgrading to v3 fixed the pipeline.

Update upload-artifact from v2 to v3

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

Similar to rust toolchain, it uses an opt-in flag `enable_go` to install the toolchain.
```
duckdb-next-build:
...
with:
...
enable_go: true
```
This is useful for building duckdb extensions in Go. 
See example repository https://github.com/ajzo90/duckdb-go-extension-example

Add opt-in go toolchain to CI extension template

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_deploy.yml
.github/workflows/_extension_distribution.yml
docker/README.md
docker/linux_amd64/Dockerfile
docker/linux_amd64_gcc4/Dockerfile
docker/linux_arm64/Dockerfile

This PR removes the `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION` flag from the Linux CI.
It achieves this by refactoring the linux jobs to manually invoke docker for the build and test steps effectively pulling out the github actions from the docker image. This has the following benefits:
- The jobs will not fail when GH stops supporting the `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION` flag
- easier to reproduce the environment locally
- more robust linux builds because we are not mixing github actions with a horribly old linux version anymore
Also during development I integrated https://github.com/duckdb/extension-ci-tools/pull/63 because I needed it, that saved me some CI cycles so I can just merge this PR and close the otherone.
There is quite some duplication between the dockerfiles, but I …

Switch to manual docker

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

Prints the build logs for any rust code that is built through cmake. Useful for issues like https://github.com/duckdb/duckdb/issues/12983

Add rust logging

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml

This PR aims to make calling the `.github/workflows/_extension_distribution.yml` workflow a little more predictable. It also fixes the CI failures that will happen whenever trying to build an extension on an old extension_ci_tools submodule after https://github.com/duckdb/extension-ci-tools/pull/79. 
What this means is that all extension will now be required to pass both a `duckdb_version` **and** a `ci_tools_version`. These will in most cases contain the same value (the tag of the latest stable release of duckdb or `main`).
The reason we need this is because we want to checkout the `extension_ci_tools` submodule of the extension to the version   of the called workflow. So for example in the following invocation of `_extension_distribution.yml`:
```yml
duckdb-stable-build:
name: Build …
```

force passing ci tools version

---

.github/workflows/_extension_distribution.yml

vcpkg doesnt detect the rtools mingw toolchain, which causes issues in the faiss extension.

Make sure vcpkg uses the rtools toolchain instead of windows mingw

---

.github/workflows/_extension_distribution.yml

I did tested on my fork, it's a bit annoying as API since it's easy to misuse, but checks are also easy to do wrong.
One one side this likely needs to be iterated on, on the other it's probably easier to just start using this and find later the patterns that do make sense.
There are notes that those settings are unstable, meant for internal use only, and easy to misuse.

Allow passing extra duckdb_tag and extension_tag internal options

---

.github/workflows/_extension_distribution.yml

Triggered by failures at https://github.com/duckdb/community-extensions/pull/128, that are independent from the extension but due to testing process implying rebuilding stuff.
This will provide an escape hatch for that extension (that can be rebuild skipping the tests), but that might be of minor but general utility to have. Especially since tests might be brittle or depend on ordering (say other extensions might be needed).

Add skip_tests input, to avoid performing testing step

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml
README.md
docker/linux_amd64/Dockerfile
docker/linux_amd64_gcc4/Dockerfile
docker/linux_arm64/Dockerfile

Python3 was not already installed in the Linux Docker containers jobs (while it's implicit in the OSX / Windows / Wasm runners).
This is a good test since it uses compilations paths with no python, that expecially on Linux might be relevant.
Still extension might want to rely on Python being there, for example [shellfs](https://community-extensions.duckdb.org/extensions/shellfs.html) used python for testing, and was now breaking.
This should address 1/3 of https://github.com/duckdb/community-extensions/issues/127

Add optional `python3` dependency and move tests to v1.1.1

---

.github/workflows/_extension_distribution.yml

This is needed otherwise passing `skip_tests` would have no extension built on Windows, see for example the CI run at: https://github.com/carlopi/community-extensions/actions/runs/11131357303

Fixup skipping of tests (skip release & test_release on Windows)

---

.github/workflows/_extension_distribution.yml
makefiles/duckdb_extension.Makefile

Idea is make room for other kind of extensions that might not have such a strict dependency / need for the duckdb submodule.
This is mostly connected to C-API extensions, but possibly also other ways of handling dependencies or other use cases can also become relevant.
Currently there are no changes that actually would allow a C-API extension, but I think overriding `set_duckdb_version`, `set_duckdb_tag` and `output_distribution_matrix` to no-op, no-op and returning a default might work fine.

Move duckdb specifics from workflow to Makefile

---

.github/workflows/_extension_distribution.yml

This Pull Request introduces a small change aimed at freeing up storage space to accommodate more complex builds, such as the BigQuery extension. The idea, its benefits, and the problem it addresses are detailed in [Issue #127](https://github.com/duckdb/community-extensions/issues/127).
The proposed changes add an extra step in the build process that removes cached docker images that are not used.

Free Up Storage Space to Support Complex Builds

---

.github/workflows/_extension_deploy.yml
.github/workflows/_extension_distribution.yml

I think depending on the repository Python requirment (possibly due to bumping version) have changed, and now naked (= non virtual environment) `pip install` or `python3 -m pip install` throw the following erorr:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment …
```

Cover Python's 'This environment is externally managed' error

---

.github/workflows/_extension_distribution.yml
scripts/append_extension_metadata.py

two minor fixes to the ci tools:
- ignore failures on space cleanup step
- make signing script work on python < 3.11

Fix space cleanup step when no imgs

---

.github/workflows/_extension_distribution.yml

We are running on arm runners now, right?

switch which macos arch runs the tests

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml
makefiles/duckdb_extension.Makefile
scripts/append_extension_metadata.py

After this PR, my experimental rust-based extension template (https://github.com/samansmink/extension-template-rs) should be one step closer to reality.
This requires some tweaks to the workflows because things like running tests and platform detection are different from the C++ api based extensions that do have a duckdb submodule in their repository.
Changes:
- you can now disable running the tests by setting the SKIP_TESTS variable
- tests on linux are now run twice: once inside docker, once outside
- there's a new `configure_ci` step which is called once inside docker, once outside
- extensions can detect which one is being called and set SKIP_TESTS for either to work around any issues
- `test_*` targets no longer automatically build too, this avoids double building that would happen
- …

Prepare ci tools for extensions without DuckDB submodule

---

makefiles/duckdb_extension.Makefile
makefiles/duckdb_extension_c_api.Makefile
makefiles/duckdb_extension_rs.Makefile
scripts/append_extension_metadata.py
scripts/configure_helper.py

This adds 2 new Makefiles:
- `makefiles/duckdb_extension_c_api.Makefile`
- `makefiles/duckdb_extension_rs.Makefile`
`duckdb_extension_c_api` contains generic config that can be reused by other C API based extension templates. `duckdb_extension_rs` contains the rust specific parts.
See https://github.com/samansmink/extension-template-rs/blob/34c045e3a03a07f159b402fb3a35053d502c7ccd/Makefile for intended use.
These makefiles should be considered unstable for now, however with this PR we should be able to finish up the Rust extension template into a working state where we can experiment with it.
- Add CI in this repository for every extension template that uses these makefiles

Add new Makefiles for experimental C API based extensions

---

docker/linux_amd64/Dockerfile
docker/linux_arm64/Dockerfile

This allows to reintegrate iceberg to be built in duckdb/duckdb CI (was removed as part of bumping vcpkg commit, that likely relies on some newer cmake behaviour in the feature detection of boost::filesystem dependency).

Bump cmake and wget packages

---

.github/workflows/_extension_distribution.yml

Given duckdb/duckdb builds since a couple of weeks with that commit it should be fine.
A given extension can always pin the vcpkg commit to a lower version if needed.

Bump vcpkg commit, to re-align to duckdb/duckdb

---

.github/workflows/TestCITools.yml
config/distribution_matrix.json
docker/linux_amd64_musl/Dockerfile

This has been tested to work for all extensions in out_of_tree_extensions.cmake but for `arrow` and `mysql_scanner`.
Connected to https://github.com/duckdb/duckdb/pull/15429, introducing the 2 musl targets, this implements building musl extensions for one of the `amd64` version.
Once this PR is in, the duckdb/duckdb PR can be updated to build extensions using the dockerfile added here, but they can go in independently.
This is currently removed from capi, rust capi, and delta, since all of them fail for different reasons to be investigated on a side.
capi -> duckdb builds with wrong platform backed in, so they are incompatible (can be lifted after https://github.com/duckdb/duckdb/pull/15429 is merged)
rust capi -> there is an error in linking to produce a dynamic library, possibly rust …

Add `linux_amd64_musl` platform

---

makefiles/c_api_extensions/base.Makefile

Currently using `DUCKDB_GIT_VERSION=main` fails for C-API extensions since main is not a valid version.
Default to latest then when installing the Pyhton-based package.
Tests of this working are at https://github.com/carlopi/extension-ci-tools/actions/runs/12633104809/job/35198062606, where a second problem is shown connected to hardcoding MINIMUM_DUCDKB_VERSION, to be solved independently.

Handle also `main` as DUCKDB_GIT_VERSION for C-API extensions

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml
config/distribution_matrix.json

This is not particularly pretty, BUT all in all I think it's the best way forward.
Basically `.github/workflows/_extension_distribution.yml` can be used either by `v1.1.3`(platfrom was called `windows_amd64_rtools`) OR `main` (platform now called `windows_amd64_mingw`), BUT for making use of this end-to-end a newer script to interpret `config/distribution_matrix.json` would have to be provided for `v1.1.x` (if we were to release again).

Allows either `_rtools`OR `_mingw` in _extension_distribution (but only mingw in the json)

---

.github/workflows/TestCITools.yml
makefiles/c_api_extensions/base.Makefile

Should fix failure in https://github.com/duckdb/extension-template-c/pull/4

Avoid testing CAPI extensions on _musl outside the container

---

docker/linux_arm64/Dockerfile

When compiling duckdb-spatial with the latest extension-ci-tools, linux_arm64 have started failing. Upon further investigation it seems like upgrading the CMake version is the culprit. Specifically, CMake 3.21 is ok, but >= 3.25 breaks.
duckdb-spatial is a bit different than other extension builds in that it doesn't entirely rely on Vcpkg for dependencies but also builds some dependencies using the "recursive cmake" technique. My guess is that something changed in cmake that affected how variables are passed down/interpreted from/to subprocesses which causes the cross-compilation toolchain to be misconfigured for the nested cmake projects, causing them to compile with the host toolchain, which eventually leads to linking errors. 
We should eventually move the rest of spatial to use only …

Revert cmake version for linux_arm64

---

.github/workflows/_extension_distribution.yml
docker/linux_arm64/Dockerfile

This PR pins the emsdk version for wasm builds to ~~3.1.74~~ 3.1.71 (4.0.0 was released just a couple days ago), which fixes some compilation issues in duckdb-spatial.
Additionally I've managed to resolve the issues related to updating CMake in arm64 builds properly in duckdb-spatial, so this PR also reverts the changes in https://github.com/duckdb/extension-ci-tools/pull/129.

Pin emsdk to 3.1.71, use latest cmake for arm64 as well

---

makefiles/c_api_extensions/c_cpp.Makefile

This allows automatically fetching the headers that are configured using TARGET_DUCKDB_VERSION.
So imagine I want to build an extension specifically for the latest unstable version of duckdb in pip which happens to be commit `5d02d69e5c`. The process will be:
First set these variables in the makefile (or pass them to it)
- `TARGET_DUCKDB_VERSION=5d02d69e5c`
- `USE_UNSTABLE_C_API=1`
- `DUCKDB_TEST_VERSION=1.1.4.dev4889`
Then:
```sh
make configure
make update_duckdb_headers
make debug
make test_debug
```

fix update headers to download correct headers

---

.github/workflows/_extension_distribution.yml

Hi DuckDB Team,  
On Linux GitHub runners, Docker currently stores its images under `/var/lib/docker`. However, the available disk space there is limited:  
```
Filesystem      Size  Used Avail Use% Mounted on  
/dev/root        72G   45G   28G  63% /  
tmpfs           7.9G   84K  7.9G   1% /dev/shm  
tmpfs           3.2G  1.1M  3.2G   1% /run  
tmpfs           5.0M     0  5.0M   0% /run/lock  
/dev/sdb16      881M   59M  761M   8% /boot  
/dev/sdb15      105M  6.1M   99M   6% /boot/efi  
/dev/sda1        74G  4.1G   66G   6% /mnt  
tmpfs           1.6G   12K  1.6G   1% /run/user/1001  
```
As shown, Docker is restricted to just 28GB of available space on `/var/lib/docker`. I’m working on an extension that requires more storage, so this patch adjusts the Docker image path to …

fix: move Docker path under `/mnt` rather than under `/` for additional disk space.

---

docker/linux_amd64_gcc4/Dockerfile

Hi DuckDB Team,  
In the `linux_amd64_gcc4` target, the default version of `curl` (7.29.0, released in 2013) is unfortunately incompatible with the command-line arguments required by `vcpkg` for caching binary artifacts using GitHub Actions. This poses a challenge for an upcoming PR that aims to enable binary caching during builds.  
To work around this issue, I’ve configured `vcpkg` to build a more recent version of `curl` directly inside the container and temporarily replace `/usr/bin/curl` with the updated version for the build process. Importantly, this version is only used during the build and is not linked or distributed with the final artifact.  
Additionally, I've raised a request with `vcpkg` to add validation for a minimum `curl` version when using binary caching, which you can …

fix: Addressing `curl` Compatibility in `linux_amd64_gcc4` for Binary Caching  

---

.github/workflows/_extension_distribution.yml

Hi DuckDB Team,  
This PR introduces support for caching `vcpkg` built artifacts using GitHub Actions. This feature, referred to as Binary Caching, is well-documented [here](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching).  
To enable caching, `vcpkg` provides a standard GitHub action step:  
```yaml
- name: Export GitHub Actions cache environment variables  
uses: actions/github-script@v7  
with:  
script: |  
core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');  
core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');  
```  
I've added this step to the workflow and adjusted the Docker environment setup to ensure builds within the container can access the cache.  
For my Airport extension, this change has …

fix: Enable `vcpkg` Binary Caching in GitHub Actions

---

docker/linux_amd64_musl/Dockerfile

Hi DuckDB Team,
For Rust builds to work with `musl` targets libunwind is required.  This PR adds it.
Rusty

fix: add libunwind

---

.github/workflows/_extension_distribution.yml

Hi DuckDB Team,
`rtools` ships a version of `curl`, that is incompatible with the code that downloads `ccache`'s saved results.  This PR sets up `ccache` before `rtools`.
Thanks,
Rusty

fix: setup `ccache` before `rtools`

---

.github/workflows/TestCITools.yml

This should possibly solve the problems @rustyconover bumped into in https://github.com/duckdb/extension-ci-tools/pull/149 with the test setup.
Unsure if Delta commit needs also changing, for not letting CI run.

Move TestCITools from 1.1.3 to 1.2.0

---

.github/workflows/_extension_distribution.yml

Fix the problem where multiple DuckDB versions would be cached in the same ccache bundle.  This should improve cache hits when building for multiple branches at the same time.

fix: add DuckDB version to ccache key

---

makefiles/duckdb_extension.Makefile

Hi there, 
I noticed I couldn't build the benchmark runner from the extension directory, so I added an option to the Makefile to do so.
It doesn't use quite the same flags as the [benchmark command](https://github.com/duckdb/duckdb/blob/f965a9d40cd0fa68d1bbd66a0e535023d1635760/Makefile#L404-L408) in `duckdb/Makefile`, is that important to align?  
Let me know if you find this useful or if I missed something and this is not the way to go :) 
Kind regards, 
Daniel

Add option to build benchmark from extension directory

---

makefiles/duckdb_extension.Makefile

I'm sorry if I miss some context behind the current setup, but it seems `duckdb_extension.Makefile` doesn't properly set the `--target` flag for `cargo`. I'm also not sure if this is sufficient to support these `DUCKDB_PLATFORM`s, but I believe this flag is necessary at least.

Set `-DRust_CARGO_TARGET=x86_64-pc-windows-gnu` when `DUCKDB_PLATFORM` is `windows_amd64_{mingw,rtools}`

---

.github/workflows/_extension_distribution.yml
docker/linux_amd64/Dockerfile
docker/linux_arm64/Dockerfile

Fixes a problem introduced by https://github.com/duckdb/extension-ci-tools/pull/190 which migrates to a new dockerfile.
Upgrading the image caused a new git version to be used, which now requires setting the git permission thingy.
Also, I've disabled vcpkg caching through github actions which was causing failures. This is to be replaced with s3 based caching

fix git permission issue in linux ci

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_code_quality.yml

Related PRs: https://github.com/duckdb/extension-template/pull/126
This PR introduces two new code quality workflows: `format-check` and `tidy-check`.  
The workflows are enabled by default, but can be disabled by extension builders by removing one or more option(s): `format_checks: 'format;tidy'`. 
It also allows us to easily expand the quality check workflow in the future if need be.

Add code quality workflows

---

.github/workflows/TestCITools.yml
.github/workflows/_extension_distribution.yml
docker/linux_amd64/Dockerfile
docker/linux_arm64/Dockerfile

This allows writing vcpkg cache to Cloudflare R2
Once R2 supports the crc64 checksum mode, we can remove this, see https://community.cloudflare.com/t/an-error-occurred-internalerror-when-calling-the-putobject-operation/764905/11

Add option to downgrade aws cli

---

.github/workflows/_extension_distribution.yml

Follow up of https://github.com/duckdb/extension-ci-tools/pull/215, now setting correct value: 'when_required' instead of unsupported ' never' value

set correct setting for disabling checksum

---

docker/linux_amd64_musl/Dockerfile

Installing ninja doesn't add it to the path on musl, so it uses some old system version by default (I think `samurai`) which doesn't work for some vcpkg dependencies that require a newer version. Adding the path explicitly fixes it.

add ninja path on musl

---

config/distribution_matrix.json
makefiles/duckdb_extension.Makefile
toolchains/x64-windows-static-md-release-vs2019comp.cmake

This change adds a new VCPKG triplet `x64-windows-static-md-release-vs2019comp` (and a toolchain definition
for it) that is intended to be used for all MSVC Windows builds (currently only `x64-windows-static-md-release`). ([reference](https://github.com/MicrosoftDocs/vcpkg-docs/blob/2b78788399105087b0488a309d565f9a033870d6/vcpkg/users/buildsystems/cmake-integration.md#vcpkg_overlay_triplets)).
This custom triplet appeared to bes necessary necessary to pass `/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` flag to AWS C++ SDK compilation. This flag enables the compatibility with older C++ stdlib from VS2019. It was added to the `duckdb/duckdb` repo in duckdb/duckdb#17991. That addition effectively propagated this flag to the extensions sources, but not to extension dependencies built with VCPKG. …

Add new triplet for Windows compatible with VS2019

---

.github/workflows/_extension_distribution.yml
docker/linux_amd64/Dockerfile
docker/linux_amd64_musl/Dockerfile
docker/linux_arm64/Dockerfile

Hi DuckDB Team,
I hope you're well. I'd like to propose an enhancement to the extension testing workflow that would provide additional flexibility.
While developing the test suite for the Airport extension, I've encountered a need to pass custom environment variables to the testing environment. This capability would allow for more flexible configuration of test parameters, particularly for specifying server URLs during testing.
The primary use case involves allowing developers to easily configure the test server URL:
- **Local Development**: Developers can point tests to a server running locally on their development machine
- **CI/CD Pipeline**: For extension releases, tests can be configured to run against our production server hosted on Google Cloud
- **Flexibility**: Other developers …

feat: Add Support for Custom Environment Variables for Extension Testing

---

.github/workflows/_extension_distribution.yml

This allows e.g. `build_type: debug` which can be useful for (CI) debugging purposes

Make build_type configurable

---

.github/workflows/_extension_distribution.yml

This dubious option is needed to run this workflow on DuckDB CI. I don't like it either but it seems to be the best way forward @carlopi

Add option to checkout duckdb to the version of the calling repo

---

.github/workflows/_extension_distribution.yml

We need the tags because duckdb's build system auto-detects versions based on it

fetch tags for duckdb caller override

---

docker/linux_amd64/Dockerfile
docker/linux_amd64_musl/Dockerfile
docker/linux_arm64/Dockerfile

To facilitate some vcpkg packages, install `libtool` by default in Dockerfiles.

fix: add libtool as a basic package

---

makefiles/duckdb_extension.Makefile

With https://github.com/duckdb/extension-ci-tools/pull/156, tests are now loaded from the `test` dir in the extension directory automatically.
We still register the extension tests again using `LOAD_TESTS`. This is no longer really required - however - the extension template and most extensions still use `LOAD_TESTS`. This causes double registration of tests that can be annoying when developing and can also get in the way when running tests from other sources (e.g. when running main DuckDB tests using `--test-dir duckdb`).
In order to move towards removing the `LOAD_TESTS` we should move towards running the extension local tests.
Another advantage here is also that the test names that get printed in CI are cleaned up (i.e. moved towards relative paths, instead of always having the …

Run tests using relative path instead of absolute path

---

makefiles/c_api_extensions/base.Makefile

This fixes the currently broken staged releases for C API extensions, since it will have CI try to install a duckdb version from a commit version that is not valid as a python version, which the C API extensions will try to install as part of the `configure_ci` step.
After this PR, C API extensions build through CI will no longer use the duckdb version from `DUCKDB_GIT_VERSION`, instead they will take the latest stable on PYPI to test. This seems fine for now to me.

remove old variable for duckdb git version
